# Site settings
title: Innvent Labs
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Innovation at Scale
baseurl: "/innvent/" # the subpath of your site, e.g. /blog/
url: "http://adityanayak.github.io" # the base hostname & protocol for your site
twitter_username: innventLabs
github_username:  innventLabs
# Build settings
markdown: kramdown
exclude: [cloud ]
