# Site settings
title: Counslr
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Innovation at Scale
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: innventLabs
github_username:  innventLabs
# Build settings
markdown: kramdown
exclude: [cloud ]
